name: Minify, Uglify and Gzip

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install terser gzip-cli

    - name: Minify and Uglify
      run: |
        npx terser src/yourfile.js -o dist/yourfile.min.js

    - name: Gzip
      run: |
        npx gzip-cli dist/yourfile.min.js -o dist/yourfile.min.js.gz

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add dist/yourfile.min.js dist/yourfile.min.js.gz
        git commit -m 'Minified, uglified, and gzipped the files'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
